
name: Hit APIs every 5 minutes

on:
  schedule:
    - cron: "* * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual run

jobs:
  ping-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Hit first URL
        run: curl -X GET https://research-mcp-9mm5.onrender.com

      - name: Hit second URL
        run: curl -X GET https://deep-insight-backend.onrender.com/docs
